In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [ ]:
from google.colab import files
uploadFile = files.upload()

Saving cars_raw (1).csv to cars_raw (1).csv

In [ ]:
temp = pd.read_csv("cars_raw.csv")
rawdf = pd.DataFrame(temp)
rawdf.isna().sum()

Year                       0
Make                       0
Model                      0
Used/New                   0
Price                      0
ConsumerRating             0
ConsumerReviews            0
SellerType                 0
SellerName                 0
SellerRating               0
SellerReviews              0
StreetName                 0
State                      0
Zipcode                    0
DealType                 222
ComfortRating              0
InteriorDesignRating       0
PerformanceRating          0
ValueForMoneyRating        0
ExteriorStylingRating      0
ReliabilityRating          0
ExteriorColor              0
InteriorColor              0
Drivetrain                 0
MinMPG                     0
MaxMPG                     0
FuelType                   0
Transmission               0
Engine                     0
VIN                        0
Stock#                     0
Mileage                    0
dtype: int64

In [ ]:
rawdf.dropna(inplace=True)
rawdf.isna().sum()

Year                     0
Make                     0
Model                    0
Used/New                 0
Price                    0
ConsumerRating           0
ConsumerReviews          0
SellerType               0
SellerName               0
SellerRating             0
SellerReviews            0
StreetName               0
State                    0
Zipcode                  0
DealType                 0
ComfortRating            0
InteriorDesignRating     0
PerformanceRating        0
ValueForMoneyRating      0
ExteriorStylingRating    0
ReliabilityRating        0
ExteriorColor            0
InteriorColor            0
Drivetrain               0
MinMPG                   0
MaxMPG                   0
FuelType                 0
Transmission             0
Engine                   0
VIN                      0
Stock#                   0
Mileage                  0
dtype: int64

In [ ]:
rawdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9157 entries, 0 to 9378
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   9157 non-null   int64
 1   Make                   9157 non-null   object
 2   Model                  9157 non-null   object
 3   Used/New               9157 non-null   object
 4   Price                  9157 non-null   object
 5   ConsumerRating         9157 non-null   float64
 6   ConsumerReviews        9157 non-null   int64
 7   SellerType             9157 non-null   object
 8   SellerName             9157 non-null   object
 9   SellerRating           9157 non-null   float64
 10  SellerReviews          9157 non-null   int64
 11  StreetName             9157 non-null   object
 12  State                  9157 non-null   object
 13  Zipcode                9157 non-null   object
 14  DealType               9157 non-null   object
 15  ComfortRating          9157 non-null   float64
 16  InteriorDesignRating   9157 non-null   float64
 17  PerformanceRating      9157 non-null   float64
 18  ValueForMoneyRating    9157 non-null   float64
 19  ExteriorStylingRating  9157 non-null   float64
 20  ReliabilityRating      9157 non-null   float64
 21  ExteriorColor          9157 non-null   object
 22  InteriorColor          9157 non-null   object
 23  Drivetrain             9157 non-null   object
 24  MinMPG                 9157 non-null   int64
 25  MaxMPG                 9157 non-null   int64
 26  FuelType               9157 non-null   object
 27  Transmission           9157 non-null   object
 28  Engine                 9157 non-null   object
 29  VIN                    9157 non-null   object
 30  Stock#                 9157 non-null   object
 31  Mileage                9157 non-null   int64
dtypes: float64(8), int64(6), object(18)
memory usage: 2.3+ MB

In [ ]:
# In rawdf.Price, there is noise which is not NaN
# If you try to convert Price data into int form without pre-processing, you will get error code
rawdf = rawdf[rawdf.Price != 'Not Priced']
rawdf['Price_int'] = rawdf.Price.str.replace('$','').str.replace(',','').astype('int')
rawdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9152 entries, 0 to 9378
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   9152 non-null   int64
 1   Make                   9152 non-null   object
 2   Model                  9152 non-null   object
 3   Used/New               9152 non-null   object
 4   Price                  9152 non-null   object
 5   ConsumerRating         9152 non-null   float64
 6   ConsumerReviews        9152 non-null   int64
 7   SellerType             9152 non-null   object
 8   SellerName             9152 non-null   object
 9   SellerRating           9152 non-null   float64
 10  SellerReviews          9152 non-null   int64
 11  StreetName             9152 non-null   object
 12  State                  9152 non-null   object
 13  Zipcode                9152 non-null   object
 14  DealType               9152 non-null   object
 15  ComfortRating          9152 non-null   float64
 16  InteriorDesignRating   9152 non-null   float64
 17  PerformanceRating      9152 non-null   float64
 18  ValueForMoneyRating    9152 non-null   float64
 19  ExteriorStylingRating  9152 non-null   float64
 20  ReliabilityRating      9152 non-null   float64
 21  ExteriorColor          9152 non-null   object
 22  InteriorColor          9152 non-null   object
 23  Drivetrain             9152 non-null   object
 24  MinMPG                 9152 non-null   int64
 25  MaxMPG                 9152 non-null   int64
 26  FuelType               9152 non-null   object
 27  Transmission           9152 non-null   object
 28  Engine                 9152 non-null   object
 29  VIN                    9152 non-null   object
 30  Stock#                 9152 non-null   object
 31  Mileage                9152 non-null   int64
 32  Price_int              9152 non-null   int64
dtypes: float64(8), int64(7), object(18)
memory usage: 2.4+ MB

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
rawdf.columns

Index(['Year', 'Make', 'Model', 'Used/New', 'Price', 'ConsumerRating',
       'ConsumerReviews', 'SellerType', 'SellerName', 'SellerRating',
       'SellerReviews', 'StreetName', 'State', 'Zipcode', 'DealType',
       'ComfortRating', 'InteriorDesignRating', 'PerformanceRating',
       'ValueForMoneyRating', 'ExteriorStylingRating', 'ReliabilityRating',
       'ExteriorColor', 'InteriorColor', 'Drivetrain', 'MinMPG', 'MaxMPG',
       'FuelType', 'Transmission', 'Engine', 'VIN', 'Stock#', 'Mileage',
       'Price_int'],
      dtype='object')

In [ ]:
rawdf.head()

,Year,Make,Model,Used/New,Price,ConsumerRating,ConsumerReviews,SellerType,SellerName,SellerRating,...,Drivetrain,MinMPG,MaxMPG,FuelType,Transmission,Engine,VIN,Stock#,Mileage,Price_int
0,2019,Toyota,Sienna SE,Used,"$39,998",4.6,45,Dealer,CarMax Murrieta - Now offering Curbside Pickup...,3.3,...,Front-wheel Drive,19,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,5TDXZ3DC2KS015402,22998646,29403,39998
1,2018,Ford,F-150 Lariat,Used,"$49,985",4.8,817,Dealer,Giant Chevrolet,4.8,...,Four-wheel Drive,19,24,Gasoline,10-Speed Automatic,3.5L V6 24V PDI DOHC Twin Turbo,1FTEW1EG2JFD44217,22418A,32929,49985
2,2017,RAM,1500 Laramie,Used,"$41,860",4.7,495,Dealer,Gill Auto Group Madera,4.6,...,Four-wheel Drive,15,21,Gasoline,8-Speed Automatic,5.7L V8 16V MPFI OHV,1C6RR7VT5HS842283,NG277871G,23173,41860
4,2020,Lexus,RX 350,Used,"$49,000",4.8,76,Dealer,Lexus of Henderson,4.8,...,Front-wheel Drive,20,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,2T2AZMAA8LC156270,HDT4181A,28137,49000
5,2012,Toyota,4Runner SR5,Used,"$23,541",4.7,34,Dealer,AutoNation Toyota Hayward,4.4,...,Rear-wheel Drive,17,23,Gasoline,5-Speed Automatic,4.0L V6 24V MPFI DOHC,JTEZU5JR3C5043790,C5043790,105469,23541

In [ ]:
target_columns = [
    'Year','ConsumerRating','ConsumerReviews','SellerRating','SellerReviews','ComfortRating',
    'InteriorDesignRating','PerformanceRating','ValueForMoneyRating','ExteriorStylingRating',
    'ReliabilityRating','MinMPG','MaxMPG','Mileage','Price_int'
]

targetDf = rawdf[target_columns]
targetDf['CarAge'] = 2022 - targetDf['Year']
targetDf.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Year,ConsumerRating,ConsumerReviews,SellerRating,SellerReviews,ComfortRating,InteriorDesignRating,PerformanceRating,ValueForMoneyRating,ExteriorStylingRating,ReliabilityRating,MinMPG,MaxMPG,Mileage,Price_int,CarAge
0,2019,4.6,45,3.3,3,4.7,4.6,4.6,4.4,4.6,4.7,19,27,29403,39998,3
1,2018,4.8,817,4.8,131,4.9,4.8,4.8,4.6,4.8,4.7,19,24,32929,49985,4
2,2017,4.7,495,4.6,249,4.8,4.7,4.8,4.6,4.8,4.7,15,21,23173,41860,5
4,2020,4.8,76,4.8,4755,4.9,4.8,4.8,4.7,4.8,4.9,20,27,28137,49000,2
5,2012,4.7,34,4.4,1071,4.7,4.6,4.4,4.6,4.9,4.9,17,23,105469,23541,10

In [ ]:
# you can change target columns and all the pre-processing code
# visualize anything you want based on the data